-- SET FOREIGN_KEY_CHECKS = 0; 
DROP DATABASE IF EXISTS battlecard_db; 
SET FOREIGN_KEY_CHECKS = 0; 
DROP TABLE IF EXISTS cards; 
DROP TABLE IF EXISTS deck; 
DROP TABLE IF EXISTS scores; 
DROP TABLE IF EXISTS users; 
SET FOREIGN_KEY_CHECKS = 1;   
CREATE DATABASE battlecard_db;